services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: movierama
      POSTGRES_USER: movierama
      POSTGRES_PASSWORD: movierama
    ports:
      - "5432:5432"
    volumes:
      - movierama_db:/var/lib/postgresql/data

volumes:
  movierama_db: